---
title: "cran-comments"
author: "Payton Jones"
date: "August 22, 2023"
output:
  md_document
---

## Test environments
* Windows Server 2022, R-devel, 64 bit (R-hub)
* Ubuntu Linux 20.04.1 LTS, R-release, GCC (R-hub)
* Fedora Linux, R-devel, clang, gfortran (R-hub)
* macOS Ventura 13.5 (local)

## R CMD Check results
There were no ERRORS or WARNINGS

On Windows, there were two NOTEs:
* checking for detritus in the temp directory ... NOTE
Found the following files/directories:
  'lastMiKTeXException'
* checking for detritus in the temp directory ... NOTE
Found the following files/directories:
  ''NULL''
  
On Ubuntu and Fedora Linux, there was one NOTE:
*  Skipping checking HTML validation: no command 'tidy' found
  
This is a known Rhub issue (https://github.com/r-hub/rhub/issues/503) 

On Ubuntu and Fedora Linux, Rhub classified the build as a PREPERROR, though appears to be a mistake. No apparent build error could be found in the logs and an OK status was returned with no errors or warnings.

## Downstream dependencies
There are 4 downstream dependencies for this package (bootnet, NetworkComparr, NetworkComparisonTest, BGGM), which passed checks.
